// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnxCDR6ZVz5O3-EST9S5Md1y18sqk_Igs',
    appId: '1:675445548984:web:9c88d07189ceae7ddb914d',
    messagingSenderId: '675445548984',
    projectId: 'nodeme-165a5',
    authDomain: 'nodeme-165a5.firebaseapp.com',
    storageBucket: 'nodeme-165a5.firebasestorage.app',
    measurementId: 'G-QS3RCB333L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKrKxWm1fBhfEtNSSBfGlY4NA_6u7-ozQ',
    appId: '1:675445548984:android:2d767c239e995b0edb914d',
    messagingSenderId: '675445548984',
    projectId: 'nodeme-165a5',
    storageBucket: 'nodeme-165a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFxmahz9rih2ZEmF_Y08F1T70Rpc55aOw',
    appId: '1:675445548984:ios:6a50884f5349fb60db914d',
    messagingSenderId: '675445548984',
    projectId: 'nodeme-165a5',
    storageBucket: 'nodeme-165a5.firebasestorage.app',
    iosBundleId: 'com.amank77.nodeMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFxmahz9rih2ZEmF_Y08F1T70Rpc55aOw',
    appId: '1:675445548984:ios:6a50884f5349fb60db914d',
    messagingSenderId: '675445548984',
    projectId: 'nodeme-165a5',
    storageBucket: 'nodeme-165a5.firebasestorage.app',
    iosBundleId: 'com.amank77.nodeMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnxCDR6ZVz5O3-EST9S5Md1y18sqk_Igs',
    appId: '1:675445548984:web:2aa012fc24b4e4a8db914d',
    messagingSenderId: '675445548984',
    projectId: 'nodeme-165a5',
    authDomain: 'nodeme-165a5.firebaseapp.com',
    storageBucket: 'nodeme-165a5.firebasestorage.app',
    measurementId: 'G-XBE3MH4ZQY',
  );
}
